version: '3'

services:
  host:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./:/app
      - host_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  remote:
    build:
      context: ../remote
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    working_dir: /app
    volumes:
      - ../remote:/app
      - remote_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  host_node_modules:
  remote_node_modules: